name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and push
    runs-on: ubuntu-latest

    working-directory: ./app-journey

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build docker image
        run: docker build -t costavictor/nlw-journey-devops:latest -f app-journey/Dockerfile .
